-- Table
-- 1. Tables: Main
Create Table Customer (
    CustomerId      Number Generated By Default As Identity Primary Key,
    CustomerName    Varchar2(50),
    CompanyName     Varchar2(50),
    Phone           Varchar2(50),
    Email           Varchar2(50),
    Address         Varchar2(500),
    CustomerType    Varchar2(20) Default 'Regular',
    MemberDiscount  Number(5,2) Default 0,
    IsDeleted       Number(1,0) Default 0
);
/
Create Table Vendor (
    VendorId    Number Generated By Default As Identity Primary Key,
    VendorName  Varchar2(50),
    CompanyName Varchar2(50),
    Phone       Varchar2(50),
    Email       Varchar2(50),
    Address     Varchar2(500),
    IsDeleted   Number(1,0) Default 0
);
/
Create Table Employee (
    EmployeeId       Number Generated By Default As Identity Primary Key,
    EmployeeName     Varchar2(50),
    Sex              Varchar2(50),
    DOB              Date,
    Address          Varchar2(500),
    MaritalStatus    Varchar2(50),
    HaveSpouse       Number(1,0),
    NumberOfChildren Number,
    HiredDate        Date,
    Position         Varchar2(50),
    Department       Varchar2(50),
    Salary           Number(12,2),
    IsActive         Number(1,0) Default 1
);
/
Create Table Item (
    ItemId          Number Generated By Default As Identity Primary Key,
    ItemName        Varchar2(100),
	Category		Varchar2(100),
    Author          Varchar2(100),
    Rating          Number(2,1),
    ItemDescription Varchar2(500),
    Quantity        Number(12,2) Default 0,
    SalePrice       Number(12,2),
    Thumbnail       Blob,
    IsDeleted       Number(1,0) Default 0
);
/
-- 2. Tables: Security
Create Table AppUser (
    AppUserId   Number Generated By Default As Identity Primary Key,
    EmployeeId  Number References Employee(EmployeeId),
    UserName    Varchar2(50) Unique,
    Password    Varchar2(100),
    Avatar      Blob,
    IsActive    Number(1,0) Default 1,
    IsAdmin     Number(1,0) Default 0
);
/
Create Table AppUserPermission (
    AppUserPermissionId Number Generated By Default As Identity Primary Key,
    AppUserId           Number References AppUser(AppUserId),
    PermissionName      Varchar2(50)
);
/
-- 3. Tables: Headers (Sales & Purchase)
Create Table Sale (
    SaleId      Number Generated By Default As Identity Primary Key,
    SaleDate    Date Default Sysdate,
    RefNumber   Varchar2(50) Unique,
    CustomerId  Number References Customer(CustomerId),
    EmployeeId  Number References Employee(EmployeeId),
    TotalAmount Number(12,2),
    Status      Varchar2(20) Default 'Completed',
    Note        Varchar2(500)
);
/
Create Table Purchase (
    PurchaseId   Number Generated By Default As Identity Primary Key,
    PurchaseDate Date Default Sysdate,
    RefNumber    Varchar2(50) Unique,
    VendorId     Number References Vendor(VendorId),
    EmployeeId   Number References Employee(EmployeeId),
    TotalAmount  Number(12,2),
    Status       Varchar2(20) Default 'Completed',
    Note         Varchar2(500)
);

-- 4. Tables: Inventory
Create Table InventoryAdjustment (
    InventoryAdjustmentId   Number Generated By Default As Identity Primary Key,
    AdjustmentDate          Date Default Sysdate,
    RefNumber               Varchar2(50),
    EmployeeId              Number References Employee(EmployeeId),
    Note                    Varchar2(500)
);
/
-- 5. Tables: Details
Create Table SaleDetail (
    SaleDetailId    Number Generated By Default As Identity Primary Key,
    SaleId          Number References Sale(SaleId),
    ItemId          Number References Item(ItemId),
    Description     Varchar2(500),
    Quantity        Number(12,2),
    UnitPriceAtSale Number(12,2),
    DiscountAmount  Number(12,2) Default 0,
    Price           Number(12,2)
);
/
Create Table PurchaseDetail (
    PurchaseDetailId Number Generated By Default As Identity Primary Key,
    PurchaseId       Number References Purchase(PurchaseId),
    ItemId           Number References Item(ItemId),
    Description      Varchar2(500),
    Quantity         Number(12,2),
    UnitPrice        Number(12,2),
	TotalAmount		 Number(12,2)
);
/
Create Table InventoryAdjustmentDetail (
    InvAdjDetailId        Number Generated By Default As Identity Primary Key,
    InventoryAdjustmentId Number References InventoryAdjustment(InventoryAdjustmentId),
    ItemId                Number References Item(ItemId),
    Description           Varchar2(500),
    Quantity              Number(12,2),
    UnitPrice        	  Number(12,2),
	TotalAmount		 	  Number(12,2)
);
/
Commit;
/
-- StoreProcedure
-- 1. AppUserGet
Create Or Replace Procedure AppUserGet
(
 P_AppUserId AppUser.AppUserId%Type Default 0
)
As
 C_AppUser Sys_RefCursor;
Begin
 If P_AppUserId = 0 Then
    Open C_AppUser For Select * From AppUser;
 Else
    Open C_AppUser For Select * From AppUser Where AppUserId = P_AppUserId;
 End If;
 DBMS_SQL.return_result(C_AppUser);
End;
/

-- 2. AppUserAdd
Create Or Replace Procedure AppUserAdd
(
 P_EmployeeId AppUser.EmployeeId%Type,
 P_UserName   AppUser.UserName%Type,
 P_Password   AppUser.Password%Type,
 P_Avatar     AppUser.Avatar%Type,
 P_IsActive   AppUser.IsActive%Type Default 1,
 P_IsAdmin    AppUser.IsAdmin%Type Default 0,
 P_AppUserId  OUT AppUser.AppUserId%Type
)
As
Begin
 Insert Into AppUser(EmployeeId, Username, Password, Avatar, IsActive, IsAdmin) 
 Values(P_EmployeeId, P_UserName, P_Password, P_Avatar, P_IsActive, P_IsAdmin)
 Returning AppUserId Into P_AppUserId;
 Commit;
End;
/

-- 3. AppUserUpdate
Create Or Replace Procedure AppUserUpdate
(
 P_AppUserId  AppUser.AppUserId%Type,
 P_EmployeeId AppUser.EmployeeId%Type,
 P_UserName   AppUser.UserName%Type,
 P_Password   AppUser.Password%Type,
 P_Avatar     AppUser.Avatar%Type,
 P_IsActive   AppUser.IsActive%Type,
 P_IsAdmin    AppUser.IsAdmin%Type
)
As
Begin
 Update AppUser
 Set EmployeeId = P_EmployeeId,
     Username = P_UserName,
     Password = P_Password,
     Avatar = P_Avatar,
     IsActive = P_IsActive,
     IsAdmin = P_IsAdmin
 Where AppUserId = P_AppUserId;
 Commit;
End;
/

-- 4. AppUserDelete (Soft Delete / Deactivate)
Create or replace Procedure AppUserDelete
(
 P_AppUserId AppUser.AppUserId%Type
)
As
Begin
 Update AppUser
 Set IsActive = 0
 Where AppUserId = P_AppUserId;
 Commit;
End;
/

-- 5. AppUserLogin
Create Or Replace Procedure AppUserLogin
(
 P_Username AppUser.Username%Type,
 P_Password AppUser.Password%Type
)
As
 C_AppUser Sys_RefCursor;
Begin
 Open C_AppUser For Select * From AppUser Where Upper(Username) = Upper(P_Username) And Password = P_Password And IsActive = 1;
 DBMS_SQL.return_result(C_AppUser);
End;
/

-- 6. AppUserPermissionGet
Create Or Replace Procedure AppUserPermissionGet
(
 P_AppUserId AppUserPermission.AppUserId%Type Default 0
)
As
 C_AppUserPermission Sys_RefCursor;
Begin
 If P_AppUserId = 0 Then
    Open C_AppUserPermission For Select * From AppUserPermission;
 Else
    Open C_AppUserPermission For Select * From AppUserPermission Where AppUserId = P_AppUserId;
 End If;
 DBMS_SQL.return_result(C_AppUserPermission);
End;
/

-- 7. AppUserPermissionAdd
Create Or Replace Procedure AppUserPermissionAdd
(
 P_AppUserId      AppUserPermission.AppUserId%Type,
 P_PermissionName AppUserPermission.PermissionName%Type
)
As
Begin
 Insert Into AppUserPermission(AppUserId, PermissionName) 
 Values(P_AppUserId, P_PermissionName);
 Commit;
End;
/

-- 8. AppUserPermissionDelete
Create Or Replace Procedure AppUserPermissionDelete
(
 P_AppUserId AppUserPermission.AppUserId%Type
)
As
Begin
 Delete From AppUserPermission Where AppUserId = P_AppUserId;
 Commit;
End;
/
-- Store Procedure
-- 1. CustomerAdd 
Create Or Replace Procedure CustomerAdd(
    P_CustomerName   Customer.CustomerName%Type,
    P_CompanyName    Customer.CompanyName%Type,
    P_Phone          Customer.Phone%Type,
    P_Email          Customer.Email%Type,
    P_Address        Customer.Address%Type,
    P_CustomerType   Customer.CustomerType%Type,
    P_MemberDiscount Customer.MemberDiscount%Type
)
As 
Begin
    Insert Into Customer(CustomerName, CompanyName, Phone, Email, Address, CustomerType, MemberDiscount, IsDeleted) 
    Values(P_CustomerName, P_CompanyName, P_Phone, P_Email, P_Address, P_CustomerType, P_MemberDiscount, 0); 
    Commit;
End;
/
-- 2. CustomerDelete (Performs Soft Delete)
Create Or Replace Procedure CustomerDelete(
    P_CustomerId IN Customer.CustomerId%Type
)
As
Begin
    Update Customer 
    Set IsDeleted = 1 
    Where CustomerId = P_CustomerId;
    Commit;
End;
/
-- 3. CustomerGet
Create Or Replace Procedure CustomerGet(
    P_CustomerId Customer.CustomerId%Type Default 0
)
As
    C_Customer Sys_RefCursor;
Begin
    If(P_CustomerId = 0) Then
        Open C_Customer For Select * From Customer Where IsDeleted = 0;
    Else
        Open C_Customer For Select * From Customer Where CustomerId = P_CustomerId AND IsDeleted = 0;
    End If;
    DBMS_SQL.return_result(C_Customer);
End;
/
-- 4. CustomerUpdate 
Create Or Replace Procedure CustomerUpdate(
    P_CustomerId     Customer.CustomerId%Type,
    P_CustomerName   Customer.CustomerName%Type,
    P_CompanyName    Customer.CompanyName%Type,
    P_Phone          Customer.Phone%Type,
    P_Email          Customer.Email%Type,
    P_Address        Customer.Address%Type,
    P_CustomerType   Customer.CustomerType%Type,
    P_MemberDiscount Customer.MemberDiscount%Type
)
As
Begin
    Update Customer
    Set 
        CustomerName   = P_CustomerName,
        CompanyName    = P_CompanyName,
        Phone          = P_Phone,
        Email          = P_Email,
        Address        = P_Address,
        CustomerType   = P_CustomerType,
        MemberDiscount = P_MemberDiscount
    Where CustomerId = P_CustomerId;
    Commit;
End;
Commit;
/
--Store Procedure
-- 1. EmployeeGet
Create Or Replace Procedure EmployeeGet (
    P_EmployeeId Employee.EmployeeId%Type Default 0
) 
As
    C_Employee Sys_RefCursor;
Begin
    If P_EmployeeId = 0 Then
        Open C_Employee For
            Select * From Employee Where IsActive = 1;
    Else
        Open C_Employee For
            Select * From Employee Where EmployeeId = P_EmployeeId;
    End If;
    DBMS_SQL.return_result(C_Employee);
End;
/
-- 2. EmployeeAdd
Create Or Replace Procedure EmployeeAdd (
    P_EmployeeName     Employee.EmployeeName%Type,
    P_Sex              Employee.Sex%Type,
    P_DOB              Employee.DOB%Type,
    P_Address          Employee.Address%Type,
    P_MaritalStatus    Employee.MaritalStatus%Type,
    P_HaveSpouse       Employee.HaveSpouse%Type,
    P_NumberOfChildren Employee.NumberOfChildren%Type,
    P_HiredDate        Employee.HiredDate%Type,
    P_Position         Employee.Position%Type,
    P_Department       Employee.Department%Type,
    P_Salary           Employee.Salary%Type,
	P_IsActive         Employee.IsActive%Type,
    P_EmployeeId       OUT Employee.EmployeeId%Type
) 
As
Begin
    Insert Into Employee (EmployeeName, Sex, DOB, Address, MaritalStatus, HaveSpouse, NumberOfChildren, HiredDate, Position, Department, Salary, IsActive)
    Values (P_EmployeeName, P_Sex, P_DOB, P_Address, P_MaritalStatus, P_HaveSpouse, P_NumberOfChildren, P_HiredDate, P_Position, P_Department, P_Salary, 1)
    Returning EmployeeId Into P_EmployeeId;
    Commit;
End;
/
-- 3. EmployeeUpdate
Create Or Replace Procedure EmployeeUpdate (
    P_EmployeeId       Employee.EmployeeId%Type,
    P_EmployeeName     Employee.EmployeeName%Type,
    P_Sex              Employee.Sex%Type,
    P_DOB              Employee.DOB%Type,
    P_Address          Employee.Address%Type,
    P_MaritalStatus    Employee.MaritalStatus%Type,
    P_HaveSpouse       Employee.HaveSpouse%Type,
    P_NumberOfChildren Employee.NumberOfChildren%Type,
    P_HiredDate        Employee.HiredDate%Type,
    P_Position         Employee.Position%Type,
    P_Department       Employee.Department%Type,
    P_Salary           Employee.Salary%Type,
    P_IsActive         Employee.IsActive%Type 
) 
As
Begin
    Update Employee 
    Set EmployeeName = P_EmployeeName,
        Sex = P_Sex,
        DOB = P_DOB,
        Address = P_Address,
        MaritalStatus = P_MaritalStatus,
        HaveSpouse = P_HaveSpouse,
        NumberOfChildren = P_NumberOfChildren,
        HiredDate = P_HiredDate,
        Position = P_Position,
        Department = P_Department,
        Salary = P_Salary,
        IsActive = P_IsActive
    Where EmployeeId = P_EmployeeId;
    Commit;
End;
/
-- 4. EmployeeDelete (Soft Delete / Deactivate)
Create Or Replace Procedure EmployeeDelete (
    P_EmployeeId Employee.EmployeeId%Type
) 
As
Begin
    Update Employee 
    Set IsActive = 0 
    Where EmployeeId = P_EmployeeId;
    Commit;
End;
/
-- StoreProcedure
-- 1.InventoryAdjustmentGet
Create Or Replace Procedure InventoryAdjustmentGet (
    P_InvAdjId InventoryAdjustment.InventoryAdjustmentId%Type Default 0
)
As
    C_InvAdj Sys_RefCursor; 
Begin
    IF P_InvAdjId = 0 Then
        Open C_InvAdj For
          Select
            IA.InventoryAdjustmentId,
            IA.AdjustmentDate,
            IA.RefNumber,
            IA.EmployeeId,
            E.EmployeeName,
            IA.Note
          From InventoryAdjustment IA 
          Left Outer Join Employee E On IA.EmployeeId = E.EmployeeId;
    Else
        Open C_InvAdj For
          Select
            IA.InventoryAdjustmentId,
            IA.AdjustmentDate,
            IA.RefNumber,
            IA.EmployeeId,
            E.EmployeeName,
            IA.Note
          From InventoryAdjustment IA 
          Left Outer Join Employee E On IA.EmployeeId = E.EmployeeId
          Where IA.InventoryAdjustmentId = P_InvAdjId;
    End If;
    DBMS_SQL.return_result(C_InvAdj);
End;
/

-- 2. InventoryAdjustmentAdd
Create Or Replace Procedure InventoryAdjustmentAdd (
  P_AdjustmentDate  InventoryAdjustment.AdjustmentDate%Type,
  P_RefNumber       InventoryAdjustment.RefNumber%Type,
  P_EmployeeId      InventoryAdjustment.EmployeeId%Type,
  P_Note            InventoryAdjustment.Note%Type,
  P_InvAdjId        OUT InventoryAdjustment.InventoryAdjustmentId%Type 
)
As
Begin
    Insert Into InventoryAdjustment(AdjustmentDate, RefNumber, EmployeeId, Note) 
    Values(P_AdjustmentDate, P_RefNumber, P_EmployeeId, P_Note)
    Returning InventoryAdjustmentId Into P_InvAdjId;
    Commit;
End;
/

-- 3. InventoryAdjustmentUpdate
Create Or Replace Procedure InventoryAdjustmentUpdate (
  P_InvAdjId        InventoryAdjustment.InventoryAdjustmentId%Type,
  P_AdjustmentDate  InventoryAdjustment.AdjustmentDate%Type,
  P_RefNumber       InventoryAdjustment.RefNumber%Type,
  P_EmployeeId      InventoryAdjustment.EmployeeId%Type,
  P_Note            InventoryAdjustment.Note%Type
)
As 
Begin
    Update InventoryAdjustment 
    Set AdjustmentDate = P_AdjustmentDate,
        RefNumber = P_RefNumber,
        EmployeeId = P_EmployeeId,
        Note = P_Note
    Where InventoryAdjustmentId = P_InvAdjId;
    Commit;
End;
/

-- 1. InvAdjDetailGet
Create Or Replace Procedure InvAdjDetailGet ( 
  P_InvAdjId InventoryAdjustment.InventoryAdjustmentId%Type
) 
As 
  C_InvAdjDetail Sys_RefCursor; 
Begin
  Open C_InvAdjDetail For 
    Select 
      InvAdjDetailId,
      InventoryAdjustmentId,
      ItemId,
      Description,
      Quantity,
      UnitPrice,
      TotalAmount
    From InventoryAdjustmentDetail Where InventoryAdjustmentId = P_InvAdjId;
  DBMS_SQL.return_result(C_InvAdjDetail); 
End;
/

-- 2. InvAdjDetailAdd
Create Or Replace Procedure InvAdjDetailAdd ( 
  P_InvAdjId          InventoryAdjustmentDetail.InventoryAdjustmentId%Type, 
  P_ItemId            InventoryAdjustmentDetail.ItemId%Type,
  P_Description       InventoryAdjustmentDetail.Description%Type,
  P_Quantity          InventoryAdjustmentDetail.Quantity%Type,
  P_UnitPrice         InventoryAdjustmentDetail.UnitPrice%Type,
  P_TotalAmount       InventoryAdjustmentDetail.TotalAmount%Type
) 
As 
Begin 
  Insert Into InventoryAdjustmentDetail(InventoryAdjustmentId, ItemId, Description, Quantity, UnitPrice, TotalAmount) 
  Values(P_InvAdjId, P_ItemId, P_Description, P_Quantity, P_UnitPrice, P_TotalAmount);
  Commit; 
End;
/

-- 3. InvAdjDetailDelete
Create Or Replace Procedure InvAdjDetailDelete ( 
  P_InvAdjId InventoryAdjustmentDetail.InventoryAdjustmentId%Type 
) 
As 
Begin 
  Delete From InventoryAdjustmentDetail Where InventoryAdjustmentId = P_InvAdjId;
  Commit; 
End;
/

-- Trigger
Create Or Replace Trigger trgInvAdjInsert 
    After Insert On InventoryAdjustmentDetail
    For Each Row
Begin
    Update Item 
    Set Quantity = Quantity + :New.Quantity 
    Where ItemId = :New.ItemId; 
End;
/
-- StoreProcedure
-- 1. ItemGet
Create Or Replace Procedure ItemGet(
    P_ItemId Item.ItemId%Type Default 0
)
As
    C_Item Sys_RefCursor;
Begin
    If (P_ItemId = 0) Then
        Open C_Item For Select * From Item Where IsDeleted = 0;
    Else
        Open C_Item For Select * From Item Where ItemId = P_ItemId AND IsDeleted = 0;
    End If;
    DBMS_SQL.return_result(C_Item);
End;
/
-- 2. ItemAdd
Create Or Replace Procedure ItemAdd(
    P_ItemName          Item.ItemName%Type,
    P_Category          Item.Category%Type,
    P_Author            Item.Author%Type,
    P_Rating            Item.Rating%Type,
    P_ItemDescription   Item.ItemDescription%Type,
    P_Quantity          Item.Quantity%Type,
    P_SalePrice         Item.SalePrice%Type,
    P_Thumbnail         Item.Thumbnail%Type,
    P_ItemId            OUT Item.ItemId%Type
)
As
Begin
    Insert Into Item(ItemName, Category, Author, Rating, ItemDescription, Quantity, SalePrice, Thumbnail, IsDeleted)
    Values (P_ItemName, P_Category, P_Author, P_Rating, P_ItemDescription, P_Quantity, P_SalePrice, P_Thumbnail, 0)
    Returning ItemId Into P_ItemId;
    Commit;
End;
/
-- 3. ItemUpdate
Create Or Replace Procedure ItemUpdate(
    P_ItemId            Item.ItemId%Type,
    P_ItemName          Item.ItemName%Type,
    P_Category          Item.Category%Type,
    P_Author            Item.Author%Type,
    P_Rating            Item.Rating%Type,
    P_ItemDescription   Item.ItemDescription%Type,
    P_Quantity          Item.Quantity%Type,
    P_SalePrice         Item.SalePrice%Type,
    P_Thumbnail         Item.Thumbnail%Type
)
As
Begin
    Update Item Set
        ItemName = P_ItemName,
        Category = P_Category,
        Author = P_Author,
        Rating = P_Rating,
        ItemDescription = P_ItemDescription,
        Quantity = P_Quantity,
        SalePrice = P_SalePrice,
        Thumbnail = P_Thumbnail
    Where ItemId = P_ItemId;
    Commit;
End;
/
-- 4. ItemDelete (Soft Delete)
Create Or Replace Procedure ItemDelete(
    P_ItemId IN Item.ItemId%Type
)
As
Begin
    Update Item 
    Set IsDeleted = 1 
    Where ItemId = P_ItemId;
    Commit;
End;
/
-- StoreProcedure
-- 1. PurchaseGet (Fetches all purchases with Vendor and Employee joins)
Create Or Replace Procedure PurchaseGet (
    P_PurchaseId Purchase.PurchaseId%Type Default 0
)
As
    C_Purchase Sys_RefCursor; 
Begin
    IF P_PurchaseId = 0 Then
        Open C_Purchase For
          Select
            Purchase.PurchaseId,
            Purchase.PurchaseDate,
            Purchase.RefNumber,
            Purchase.VendorId,
            Vendor.VendorName,
            Purchase.EmployeeId,
            Employee.EmployeeName,
            Purchase.TotalAmount,
            Purchase.Status,
            Purchase.Note
          From Purchase Left Outer Join Vendor
            On Purchase.VendorId = Vendor.VendorId
          Left Outer Join Employee
            On Purchase.EmployeeId = Employee.EmployeeId;
    Else
        Open C_Purchase For
          Select
            Purchase.PurchaseId,
            Purchase.PurchaseDate,
            Purchase.RefNumber,
            Purchase.VendorId,
            Vendor.VendorName,
            Purchase.EmployeeId,
            Employee.EmployeeName,
            Purchase.TotalAmount,
            Purchase.Status,
            Purchase.Note
          From Purchase Left Outer Join Vendor
            On Purchase.VendorId = Vendor.VendorId
          Left Outer Join Employee
            On Purchase.EmployeeId = Employee.EmployeeId
          Where Purchase.PurchaseId = P_PurchaseId;
    End If;
    DBMS_SQL.return_result(C_Purchase);
End;
/

-- 2. PurchaseAdd
Create Or Replace Procedure PurchaseAdd (
  P_PurchaseDate  Purchase.PurchaseDate%Type,
  P_RefNumber     Purchase.RefNumber%Type,
  P_VendorId      Purchase.VendorId%Type,
  P_EmployeeId    Purchase.EmployeeId%Type,
  P_TotalAmount   Purchase.TotalAmount%Type, 
  P_Status        Purchase.Status%Type,
  P_Note          Purchase.Note%Type,
  P_PurchaseId    OUT Purchase.PurchaseId%Type 
)
As 
Begin
    Insert Into Purchase(PurchaseDate, RefNumber, VendorId, EmployeeId, TotalAmount, Status, Note) 
    Values(P_PurchaseDate, P_RefNumber, P_VendorId, P_EmployeeId, P_TotalAmount, P_Status, P_Note)
    Returning PurchaseId Into P_PurchaseId;
    Commit;
End;
/
-- 3. PurchaseUpdate
Create Or Replace Procedure PurchaseUpdate (
    P_PurchaseId   Purchase.PurchaseId%Type,
    P_PurchaseDate Purchase.PurchaseDate%Type,
    P_RefNumber    Purchase.RefNumber%Type,
    P_VendorId     Purchase.VendorId%Type,
    P_EmployeeId   Purchase.EmployeeId%Type,
    P_TotalAmount  Purchase.TotalAmount%Type,
    P_Status       Purchase.Status%Type,
    P_Note         Purchase.Note%Type
) 
As
Begin
    Update Purchase 
    Set PurchaseDate = P_PurchaseDate,
        RefNumber = P_RefNumber,
        VendorId = P_VendorId,
        EmployeeId = P_EmployeeId,
        TotalAmount = P_TotalAmount,
        Status = P_Status,
        Note = P_Note
    Where PurchaseId = P_PurchaseId;
    Commit;
End;
/
-- 4. PurchaseDelete(SoftDelete Cancelled)
Create Or Replace Procedure PurchaseDelete (
  P_PurchaseId Purchase.PurchaseId%Type 
)
AS
Begin
  Update Purchase 
  Set Status = 'Cancelled' 
  Where PurchaseId = P_PurchaseId;
  
  Commit;
End;
/
-- Store Procedure PurchaseDetail
-- 1. PurchaseDetailGet
Create Or Replace Procedure PurchaseDetailGet ( 
  P_PurchaseId Purchase.PurchaseId%Type
) 
As 
  C_PurDetail Sys_RefCursor; 
Begin
  Open C_PurDetail For 
    Select 
      PurchaseDetailId,
      PurchaseId,
      ItemId,
      Description,
      Quantity,
      UnitPrice,
	  TotalAmount
    From PurchaseDetail Where PurchaseId = P_PurchaseId;
  DBMS_SQL.return_result(C_PurDetail); 
End;
/

-- 2. PurchaseDetailAdd
Create Or Replace Procedure PurchaseDetailAdd ( 
  P_PurchaseId  PurchaseDetail.PurchaseId%Type, 
  P_ItemId      PurchaseDetail.ItemId%Type,
  P_Description PurchaseDetail.Description%Type,
  P_Quantity    PurchaseDetail.Quantity%Type,
  P_UnitPrice   PurchaseDetail.UnitPrice%Type,
  P_TotalAmount PurchaseDetail.TotalAmount%Type
) 
As 
Begin 
  Insert Into PurchaseDetail(PurchaseId, ItemId, Description, Quantity, UnitPrice, TotalAmount) 
  Values(P_PurchaseId, P_ItemId, P_Description, P_Quantity, P_UnitPrice, P_TotalAmount);
  Commit; 
End;
/

-- 3. PurchaseDetailDelete
Create Or Replace Procedure PurchaseDetailDelete ( 
  P_PurchaseId PurchaseDetail.PurchaseId%Type 
) 
As 
Begin 
  Delete From PurchaseDetail Where PurchaseId = P_PurchaseId;
  Commit; 
End;
/

-- TRIGGER: 
Create Or Replace Trigger trgPurchaseInsert 
    After Insert On PurchaseDetail
    For Each Row
Begin
    Update Item Set Quantity = Quantity + :New.Quantity 
    Where ItemId = :New.ItemId; 
End;
/
Create Or Replace Trigger trgPurchaseDelete 
    After Delete On PurchaseDetail
    For Each Row
Begin
    Update Item Set Quantity = Quantity - :Old.Quantity 
    Where ItemId = :Old.ItemId; 
End;
/
Create Or Replace Trigger trgPurchaseCancelStatus
    After Update Of Status On Purchase
    For Each Row
    When (Old.Status != 'Cancelled' AND New.Status = 'Cancelled')
Begin
    For r In (Select ItemId, Quantity From PurchaseDetail Where PurchaseId = :New.PurchaseId) Loop
        Update Item 
        Set Quantity = Quantity - r.Quantity
        Where ItemId = r.ItemId;
    End Loop;
End;
/
-- Store Procedure Sale
-- 1. SaleGet
Create Or Replace Procedure SaleGet (
    P_SaleId Sale.SaleId%Type Default 0
)
As 
    C_Sale Sys_RefCursor; 
Begin
    IF P_SaleId = 0 Then
    Open C_Sale For
      Select
        Sale.SaleId,
        Sale.SaleDate,
        Sale.RefNumber,
        Sale.CustomerId,
        Customer.CustomerName,
        Sale.EmployeeId,
        Employee.EmployeeName,
        Sale.TotalAmount,
        Sale.Status,
        Sale.Note
      From Sale Left Outer Join Customer
        On Sale.CustomerId = Customer.CustomerId
      Left Outer Join Employee
        On Sale.EmployeeId = Employee.EmployeeId;
  Else
    Open C_Sale For
      Select
        Sale.SaleId,
        Sale.SaleDate,
        Sale.RefNumber,
        Sale.CustomerId,
        Customer.CustomerName,
        Sale.EmployeeId,
        Employee.EmployeeName,
        Sale.TotalAmount,
        Sale.Status,
        Sale.Note
      From Sale Left Outer Join Customer
        On Sale.CustomerId = Customer.CustomerId
      Left Outer Join Employee
        On Sale.EmployeeId = Employee.EmployeeId
      Where Sale.SaleId = P_SaleId;
  End If;
  DBMS_SQL.return_result(C_Sale);
End;
/

-- 2. SaleAdd
Create Or Replace Procedure SaleAdd (
  P_SaleDate      Sale.SaleDate%Type,
  P_RefNumber     Sale.RefNumber%Type,
  P_CustomerId    Sale.CustomerId%Type,
  P_EmployeeId    Sale.EmployeeId%Type,
  P_TotalAmount   Sale.TotalAmount%Type,
  P_Status        Sale.Status%Type,
  P_Note          Sale.Note%Type,
  P_SaleId        OUT Sale.SaleId%Type 
)
As 
Begin
    Insert Into Sale(SaleDate, RefNumber, CustomerId, EmployeeId, TotalAmount, Status, Note) 
    Values(P_SaleDate, P_RefNumber, P_CustomerId, P_EmployeeId, P_TotalAmount, P_Status, P_Note)
    Returning SaleId Into P_SaleId;
    Commit;
End;
/

-- 3. SaleUpdate
Create or Replace Procedure SaleUpdate (
  P_SaleId        Sale.SaleId%Type,
  P_SaleDate      Sale.SaleDate%Type,
  P_RefNumber     Sale.RefNumber%Type,
  P_CustomerId    Sale.CustomerId%Type,
  P_EmployeeId    Sale.EmployeeId%Type, 
  P_TotalAmount   Sale.TotalAmount%Type,
  P_Status        Sale.Status%Type,
  P_Note          Sale.Note%Type
)
AS
Begin
  Update Sale Set 
    SaleDate = P_SaleDate,
    RefNumber = P_RefNumber,
    CustomerId = P_CustomerId,
    EmployeeId = P_EmployeeId,
    TotalAmount = P_TotalAmount,
    Status = P_Status,
    Note = P_Note
  Where SaleId = P_SaleId;
  Commit;
End;
/

-- 4. SaleDelete(SoftDelete)
Create Or Replace Procedure SaleDelete (
  P_SaleId Sale.SaleId%Type 
)
AS
Begin
  Update Sale 
  Set Status = 'Cancelled' 
  Where SaleId = P_SaleId;
  
  Commit;
End;
/

-- Store Procedure SaleDetail
-- 1. SaleDetailGet
Create Or Replace Procedure SaleDetailGet ( 
  P_SaleId Sale.SaleId%Type
) 
As 
  C_SaleDetail Sys_RefCursor; 
Begin
  Open C_SaleDetail For 
    Select 
      SaleDetailId,
      SaleId,
      ItemId,
      Description,
      Quantity,
      UnitPriceAtSale,
      DiscountAmount,
      Price
    From SaleDetail Where SaleId = P_SaleId;
  DBMS_SQL.return_result(C_SaleDetail); 
End;
/
-- 2. SaleDetailAdd
Create Or Replace Procedure SaleDetailAdd ( 
  P_SaleId            SaleDetail.SaleId%Type, 
  P_ItemId            SaleDetail.ItemId%Type,
  P_Description       SaleDetail.Description%Type,
  P_Quantity          SaleDetail.Quantity%Type,
  P_UnitPriceAtSale   SaleDetail.UnitPriceAtSale%Type,
  P_DiscountAmount    SaleDetail.DiscountAmount%Type,
  P_Price             SaleDetail.Price%Type
) 
As 
Begin 
  Insert Into SaleDetail(SaleId, ItemId, Description, Quantity, UnitPriceAtSale, DiscountAmount, Price) 
  Values(P_SaleId, P_ItemId, P_Description, P_Quantity, P_UnitPriceAtSale, P_DiscountAmount, P_Price);
  Commit; 
End;
/

-- 3. SaleDetailDelete
Create Or Replace Procedure SaleDetailDelete ( 
  P_SaleId  SaleDetail.SaleId%Type 
) 
As 
Begin 
  Delete From SaleDetail Where SaleId = P_SaleId;
  Commit; 
End;
/

-- 1. CustomerGet
Create Or Replace Procedure CustomerGet (P_CustomerId Customer.CustomerId%Type Default 0) As
  C_Customer Sys_RefCursor; 
Begin 
  If(P_CustomerId = 0) Then 
    Open C_Customer For Select * From Customer; 
  Else 
    Open C_Customer For Select * From Customer Where CustomerId = P_CustomerId; 
  End If; 
  DBMS_SQL.return_result(C_Customer); 
End;
/

-- 1.EmployeeGet
Create Or Replace Procedure EmployeeGet (P_EmployeeId Employee.EmployeeId%Type Default 0) As 
  C_Employee Sys_RefCursor; 
Begin 
  If(P_EmployeeId = 0) Then 
    Open C_Employee For Select * From Employee; 
  Else 
    Open C_Employee For Select * From Employee Where EmployeeId = P_EmployeeId; 
  End If; 
  DBMS_SQL.return_result(C_Employee); 
End;
/

-- 1.ItemGet
Create Or Replace Procedure ItemGet (P_ItemId Item.ItemId%Type Default 0) As
  C_Item Sys_RefCursor; 
Begin 
  If(P_ItemId = 0) Then 
    Open C_Item For Select * From Item; 
  Else 
    Open C_Item For Select * From Item Where ItemId = P_ItemId; 
  End If; 
  DBMS_SQL.return_result(C_Item); 
End;
/

-- Triggers
Create Or Replace Trigger trgSaleInsert 
    After Insert On SaleDetail
    For Each Row
Begin
    Update Item Set Quantity = Quantity - :New.Quantity 
    Where ItemId = :New.ItemId; 
End;
/

Create Or Replace Trigger trgSaleDelete 
    After Delete On SaleDetail
    For Each Row
Begin
    Update Item Set Quantity = Quantity + :Old.Quantity 
    Where ItemId = :Old.ItemId; 
End;
/
Create Or Replace Trigger trgSaleCancelStatus
    After Update Of Status On Sale
    For Each Row
    When (Old.Status != 'Cancelled' AND New.Status = 'Cancelled')
Begin
    For r In (Select ItemId, Quantity From SaleDetail Where SaleId = :New.SaleId) Loop
        Update Item 
        Set Quantity = Quantity + r.Quantity 
        Where ItemId = r.ItemId;
    End Loop;
End;
/
--Store Procedure
-- 1. VendorGet
Create Or Replace Procedure VendorGet (
    P_VendorId Vendor.VendorId%Type Default 0
) 
As
    C_Vendor Sys_RefCursor;
Begin
    If P_VendorId = 0 Then
        Open C_Vendor For Select * From Vendor Where IsDeleted = 0;
    Else
        Open C_Vendor For Select * From Vendor Where VendorId = P_VendorId AND IsDeleted = 0;
    End If;
    DBMS_SQL.return_result(C_Vendor);
End;
/

-- 2. VendorAdd
Create Or Replace Procedure VendorAdd (
    P_VendorName  Vendor.VendorName%Type,
    P_CompanyName Vendor.CompanyName%Type,
    P_Phone       Vendor.Phone%Type,
    P_Email       Vendor.Email%Type,
    P_Address     Vendor.Address%Type,
    P_VendorId    OUT Vendor.VendorId%Type
) 
As
Begin
    Insert Into Vendor (VendorName, CompanyName, Phone, Email, Address, IsDeleted)
    Values (P_VendorName, P_CompanyName, P_Phone, P_Email, P_Address, 0)
    Returning VendorId Into P_VendorId;
    Commit;
End;
/

-- 3. VendorUpdate
Create Or Replace Procedure VendorUpdate (
    P_VendorId    Vendor.VendorId%Type,
    P_VendorName  Vendor.VendorName%Type,
    P_CompanyName Vendor.CompanyName%Type,
    P_Phone       Vendor.Phone%Type,
    P_Email       Vendor.Email%Type,
    P_Address     Vendor.Address%Type
) 
As
Begin
    Update Vendor 
    Set VendorName = P_VendorName,
        CompanyName = P_CompanyName,
        Phone = P_Phone,
        Email = P_Email,
        Address = P_Address
    Where VendorId = P_VendorId;
    Commit;
End;
/

-- 4. VendorDelete (Soft Delete)
Create Or Replace Procedure VendorDelete (
    P_VendorId Vendor.VendorId%Type
) 
As
Begin
    Update Vendor 
    Set IsDeleted = 1 
    Where VendorId = P_VendorId;
    Commit;
End;
/

-- Data
SET DEFINE OFF;

-- 1. Insert Employees
INSERT INTO Employee (EmployeeId, EmployeeName, Sex, DOB, Address, MaritalStatus, HiredDate, Position, Department, Salary, IsActive) 
VALUES (1, 'Vicheka Vann', 'Male', TO_DATE('1990-11-20', 'YYYY-MM-DD'), 'Phnom Penh', 'Married', TO_DATE('2021-06-01', 'YYYY-MM-DD'), 'Store Manager', 'Store Operations', 800.00, 1);

INSERT INTO Employee (EmployeeId, EmployeeName, Sex, DOB, Address, MaritalStatus, HiredDate, Position, Department, Salary, IsActive) 
VALUES (2, 'Srey Rath', 'Female', TO_DATE('1998-05-12', 'YYYY-MM-DD'), 'Phnom Penh', 'Single', TO_DATE('2023-01-15', 'YYYY-MM-DD'), 'Lead Cashier', 'Store Operations', 450.00, 1);


-- 2. Insert App Users (Login credentials)
-- Admin Account (admin / admin123)
INSERT INTO AppUser (AppUserId, EmployeeId, UserName, Password, IsActive, IsAdmin) 
VALUES (1, 1, 'admin', 'admin123', 1, 1);

-- Cashier Account (cashier / cashier123)
INSERT INTO AppUser (AppUserId, EmployeeId, UserName, Password, IsActive, IsAdmin) 
VALUES (2, 2, 'cashier', 'cashier123', 1, 0);


-- 3. Assign Permissions to Cashier
INSERT INTO AppUserPermission (AppUserId, PermissionName) VALUES (2, 'CustomerView');
INSERT INTO AppUserPermission (AppUserId, PermissionName) VALUES (2, 'SaleView');
INSERT INTO AppUserPermission (AppUserId, PermissionName) VALUES (2, 'SaleCreate');
INSERT INTO AppUserPermission (AppUserId, PermissionName) VALUES (2, 'PurchaseView');
INSERT INTO AppUserPermission (AppUserId, PermissionName) VALUES (2, 'ItemView');


-- 4. Insert Customers (Includes Walk-in and VIP with 10% discount)
INSERT INTO Customer (CustomerName, CompanyName, Phone, Email, Address, CustomerType, MemberDiscount, IsDeleted) 
VALUES ('Walk-in Customer', 'General Public', '000-000-0000', 'walkin@bookshop.com', 'Store Counter', 'Regular', 0.00, 0);

INSERT INTO Customer (CustomerName, CompanyName, Phone, Email, Address, CustomerType, MemberDiscount, IsDeleted) 
VALUES ('Dara Chan', 'Khmer Tech Corp', '+855 12 345 678', 'dara.chan@khmertech.com', 'Phnom Penh', 'VIP', 10.00, 0);


-- 5. Insert Vendors (Publishers)
INSERT INTO Vendor (VendorName, CompanyName, Phone, Email, Address, IsDeleted) 
VALUES ('Mengly Hok', 'Nadi Books Publishing', '+855 23 211 555', 'contact@nadibooks.com', 'Preah Monivong Blvd, Phnom Penh', 0);


-- 6. Insert Book Items (Pre-stocked with quantities for POS and testing)
INSERT INTO Item (ItemId, ItemName, Category, Author, Rating, ItemDescription, Quantity, SalePrice, IsDeleted) 
VALUES (1, 'Clean Code', 'Science & Technology', 'Robert C. Martin', 4.8, 'A handbook of agile software craftsmanship.', 20, 35.00, 0);

INSERT INTO Item (ItemId, ItemName, Category, Author, Rating, ItemDescription, Quantity, SalePrice, IsDeleted) 
VALUES (2, 'Atomic Habits', 'Business & Economics', 'James Clear', 4.9, 'Tiny changes, remarkable results for personal growth.', 15, 20.00, 0);

INSERT INTO Item (ItemId, ItemName, Category, Author, Rating, ItemDescription, Quantity, SalePrice, IsDeleted) 
VALUES (3, 'Kouprey (Wild Ox)', 'Fiction', 'Sok Chandara', 4.5, 'Classic Cambodian novel depicting rural life and folklore.', 10, 12.50, 0);

COMMIT;