-- Table

-- 1. Tables: Main
Create Table Customer (
    CustomerId      Number Generated By Default As Identity Primary Key,
    CustomerName    Varchar2(50),
    CompanyName     Varchar2(50),
    Phone           Varchar2(50),
    Email           Varchar2(50),
    Address         Varchar2(500),
    CustomerType    Varchar2(20) Default 'Regular',
    MemberDiscount  Number(5,2) Default 0,
    IsDeleted       Number(1,0) Default 0
);
/
Create Table Vendor (
    VendorId    Number Generated By Default As Identity Primary Key,
    VendorName  Varchar2(50),
    CompanyName Varchar2(50),
    Phone       Varchar2(50),
    Email       Varchar2(50),
    Address     Varchar2(500),
    IsDeleted   Number(1,0) Default 0
);
/
Create Table Employee (
    EmployeeId       Number Generated By Default As Identity Primary Key,
    EmployeeName     Varchar2(50),
    Sex              Varchar2(50),
    DOB              Date,
    Address          Varchar2(500),
    MaritalStatus    Varchar2(50),
    HaveSpouse       Number(1,0),
    NumberOfChildren Number,
    HiredDate        Date,
    Position         Varchar2(50),
    Department       Varchar2(50),
    Salary           Number(12,2),
    IsActive         Number(1,0) Default 1
);
/
Create Table Item (
    ItemId          Number Generated By Default As Identity Primary Key,
    ItemName        Varchar2(100),
	Category		Varchar2(100),
    Author          Varchar2(100),
    Rating          Number(2,1),
    ItemDescription Varchar2(500),
    Quantity        Number(12,2) Default 0,
    SalePrice       Number(12,2),
    Thumbnail       Blob,
    IsDeleted       Number(1,0) Default 0
);
/
-- 2. Tables: Security
Create Table AppUser (
    AppUserId   Number Generated By Default As Identity Primary Key,
    UserName    Varchar2(50) Unique,
    Password    Varchar2(100),
    Avatar      Blob,
    IsActive    Number(1,0) Default 1,
    IsAdmin     Number(1,0) Default 0
);
/
Create Table AppUserPermission (
    AppUserPermissionId Number Generated By Default As Identity Primary Key,
    AppUserId           Number References AppUser(AppUserId),
    PermissionName      Varchar2(50)
);
/
-- 3. Tables: Headers (Sales & Purchase)
Create Table Sale (
    SaleId      Number Generated By Default As Identity Primary Key,
    SaleDate    Date Default Sysdate,
    RefNumber   Varchar2(50) Unique,
    CustomerId  Number References Customer(CustomerId),
    EmployeeId  Number References Employee(EmployeeId),
    TotalAmount Number(12,2),
    Status      Varchar2(20) Default 'Completed',
    Note        Varchar2(500)
);
/
Create Table Purchase (
    PurchaseId   Number Generated By Default As Identity Primary Key,
    PurchaseDate Date Default Sysdate,
    RefNumber    Varchar2(50) Unique,
    VendorId     Number References Vendor(VendorId),
    EmployeeId   Number References Employee(EmployeeId),
    TotalAmount  Number(12,2),
    Status       Varchar2(20) Default 'Completed',
    Note         Varchar2(500)
);

-- 4. Tables: Inventory
Create Table InventoryAdjustment (
    InventoryAdjustmentId   Number Generated By Default As Identity Primary Key,
    AdjustmentDate          Date Default Sysdate,
    RefNumber               Varchar2(50),
    EmployeeId              Number References Employee(EmployeeId),
    Note                    Varchar2(500)
);
/
-- 5. Tables: Details
Create Table SaleDetail (
    SaleDetailId    Number Generated By Default As Identity Primary Key,
    SaleId          Number References Sale(SaleId),
    ItemId          Number References Item(ItemId),
    Description     Varchar2(500),
    Quantity        Number(12,2),
    UnitPriceAtSale Number(12,2),
    DiscountAmount  Number(12,2) Default 0,
    Price           Number(12,2)
);

Create Table PurchaseDetail (
    PurchaseDetailId Number Generated By Default As Identity Primary Key,
    PurchaseId       Number References Purchase(PurchaseId),
    ItemId           Number References Item(ItemId),
    Description      Varchar2(500),
    Quantity         Number(12,2),
    UnitPrice        Number(12,2),
	TotalAmount		 Number(12,2)
);
/
Create Table InventoryAdjustmentDetail (
    InvAdjDetailId        Number Generated By Default As Identity Primary Key,
    InventoryAdjustmentId Number References InventoryAdjustment(InventoryAdjustmentId),
    ItemId                Number References Item(ItemId),
    Description           Varchar2(500),
    Quantity              Number(12,2),
    UnitPrice        	  Number(12,2),
	TotalAmount		 	  Number(12,2)
);
/
Commit;